import { z } from "zod";
const normalizedEmail = z.preprocess(v => typeof v === "string" ? v.trim().toLowerCase() : v, z.string().email().max(254));
export const registerSchema = z.object({ name: z.string().trim().min(2).max(80), email: normalizedEmail, password: z.string().min(10).max(128) });
export const loginSchema = z.object({ email: normalizedEmail, password: z.string().min(1).max(128) });
export const moduleCreateSchema = z.object({ title: z.string().trim().min(1).max(100), subtitle: z.string().trim().max(140).optional(), days: z.number().int().min(1).max(100), activities: z.array(z.string().trim().max(60)).min(1).max(7) });
export const moduleUpdateSchema = moduleCreateSchema.partial().extend({ moduleId: z.string().cuid() });
export const checkSchema = z.object({ moduleId: z.string().cuid(), day: z.number().int().min(1), activityIdx: z.number().int().min(0).max(6) });
export const noteSchema = z.object({ moduleId: z.string().cuid(), phaseKey: z.string().trim().min(1).max(80), content: z.string().max(2000) });
export const startSchema = z.object({ moduleId: z.string().cuid(), startDate: z.string().date().nullable() });
export const adminUserSchema = z.object({ userId: z.string().cuid(), role: z.enum(["USER", "ADMIN"]).optional(), status: z.enum(["ACTIVE", "SUSPENDED"]).optional() }).refine(v => v.role || v.status);
export const settingSchema = z.object({ key: z.string().regex(/^[a-z][a-z0-9_.-]{1,49}$/), value: z.string().max(500) });
