"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
type U={id:string;name:string;email:string;role:string;status:string;createdAt:string;_count:{modules:number}};
type Setting={key:string;value:string};
export default function Admin(){
 const router=useRouter(),[users,setUsers]=useState<U[]>([]),[settings,setSettings]=useState<Setting[]>([]),[error,setError]=useState("");
 async function load(){const s=await fetch('/api/auth/session');if(!s.ok)return router.replace('/login');const j=await s.json();if(j.user.role!=='ADMIN')return router.replace('/dashboard');const [u,f]=await Promise.all([fetch('/api/admin/users'),fetch('/api/admin/settings')]);setUsers(await u.json());setSettings(await f.json())}
 useEffect(()=>{load()},[]);
 async function post(path:string,body:object){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),j=await r.json();if(!r.ok){setError(j.error);return}setError('');await load()}
 async function saveSetting(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await post('/api/admin/settings',{key:f.get('key'),value:f.get('value')});e.currentTarget.reset()}
 return <div className="shell"><header className="top"><div className="brand"><small>CONTROL PANEL</small>Admin Tracker</div></header><main className="content"><section className="hero"><div><div className="eyebrow">Akses admin</div><h1>Pengguna</h1><p className="muted">Atur status dan peran. Admin aktif terakhir selalu dilindungi.</p></div></section>{error&&<p className="error">{error}</p>}<section className="card table-wrap"><table className="admin-table"><thead><tr><th>Pengguna</th><th>Tracker</th><th>Peran</th><th>Status</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.name}</b><br/><span className="muted">{u.email}</span></td><td>{u._count.modules}</td><td><select value={u.role} onChange={e=>post('/api/admin/users',{userId:u.id,role:e.target.value})}><option>USER</option><option>ADMIN</option></select></td><td><select value={u.status} onChange={e=>post('/api/admin/users',{userId:u.id,status:e.target.value})}><option>ACTIVE</option><option>SUSPENDED</option></select></td></tr>)}</tbody></table></section><section className="card"><b>Pengaturan fitur</b><p className="muted">Konfigurasi key/value tersimpan di database dan hanya dapat diubah admin.</p>{settings.map(s=><div className="row between" key={s.key}><code>{s.key}</code><b>{s.value}</b></div>)}<form onSubmit={saveSetting}><div className="field"><label>Key</label><input name="key" required pattern="[a-z0-9._-]+" placeholder="registration.enabled"/></div><div className="field"><label>Value</label><input name="value" required placeholder="true"/></div><button className="primary">Simpan pengaturan</button></form></section></main><nav className="bottom-nav"><Link href="/dashboard">Tracker</Link><Link className="active" href="/admin">Admin</Link></nav></div>
}
