"use client";

import AppHeader from "@/components/AppHeader";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { AlertTriangle, Copy, Plus, RefreshCw, Send, ShieldCheck, UserRoundPlus, UsersRound } from "lucide-react";

type User = { name: string; email: string; role: string };
type Summary = { workspace: { id: string; name: string }; role: string; entitlements: { plan: string; maxClients: number }; clientCount: number };
type Client = { id: string; status: string; client: { name: string; email: string }; risk: null | { score: number; level: string; reasons: Array<{ label: string }> }; metrics: null | { completion: number; inactivityDays: number } };
type Detail = Client & { programs: Array<{ id: string; title: string }>; interventions: Array<{ id: string; type: string; content: string; createdAt: string }> };
const headers = { "Content-Type": "application/json" };
const nudgeTemplates = ["Apa satu langkah kecil yang bisa Anda selesaikan hari ini?", "Progress sempat melambat. Mari mulai lagi dari aktivitas termudah.", "Anda hampir kembali ke ritme. Pilih satu check-in untuk diselesaikan sekarang."];

export default function CoachDashboard() {
  const [user,setUser]=useState<User|null>(null),[summary,setSummary]=useState<Summary|null>(null),[clients,setClients]=useState<Client[]>([]),[detail,setDetail]=useState<Detail|null>(null);
  const [range,setRange]=useState<7|30>(7),[email,setEmail]=useState(""),[inviteUrl,setInviteUrl]=useState(""),[content,setContent]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true);
  const load=useCallback(async()=>{setLoading(true);setError("");const s=await fetch('/api/auth/session');if(s.status===401){location.href='/login';return}const sd=await s.json();setUser(sd.user);const r=await fetch('/api/coach/workspace');const d=await r.json();setSummary(d.summary);if(d.summary){const c=await fetch(`/api/coach/clients?workspaceId=${d.summary.workspace.id}&range=${range}`);const cd=await c.json();if(c.ok)setClients(cd.clients);else setError(cd.error||'Gagal memuat client')}setLoading(false)},[range]);
  useEffect(()=>{load()},[load]);
  async function createWorkspace(){const r=await fetch('/api/coach/workspace',{method:'POST',headers,body:JSON.stringify({name:`${user?.name||'Coach'} Coach Workspace`})});if(!r.ok)setError((await r.json()).error||'Gagal membuat workspace');else load()}
  async function invite(){if(!summary)return;setError("");const r=await fetch('/api/coach/invites',{method:'POST',headers,body:JSON.stringify({workspaceId:summary.workspace.id,clientEmail:email})});const d=await r.json();if(!r.ok){setError(d.error==='COACH_PLAN_REQUIRED'?'Upgrade Coach Pro diperlukan untuk mengundang client':d.error||'Invite gagal');return}setInviteUrl(d.inviteUrl);setEmail('');load()}
  async function openClient(linkId:string){if(!summary)return;const r=await fetch(`/api/coach/client?workspaceId=${summary.workspace.id}&linkId=${linkId}&range=${range}`);const d=await r.json();if(r.ok)setDetail(d);else setError(d.error||'Client tidak tersedia')}
  async function intervention(type:'PRIVATE_NOTE'|'NUDGE'){if(!summary||!detail||!content.trim())return;const r=await fetch('/api/coach/interventions',{method:'POST',headers,body:JSON.stringify({workspaceId:summary.workspace.id,linkId:detail.id,type,content})});if(!r.ok){setError((await r.json()).error||'Gagal mencatat intervensi');return}setContent('');openClient(detail.id)}
  async function revoke(){if(!summary||!detail||!confirm('Cabut akses Coach ke progres client ini?'))return;await fetch('/api/coach/revoke',{method:'POST',headers,body:JSON.stringify({workspaceId:summary.workspace.id,linkId:detail.id})});setDetail(null);load()}
  if(loading)return <main className="auth-shell"><div className="eyebrow">Memuat Coach Mode...</div></main>;
  return <div className="shell dashboard-shell coach-shell"><AppHeader user={user} active="coach" onLogout={()=>location.href='/logout'}/><main className="content dashboard-content">
    <section className="hero dashboard-hero"><div><div className="eyebrow">Coach Mode</div><h1>Accountability command center</h1><p className="muted">Pantau progres yang disetujui client. Private reflection dan Daily Plan tetap tersembunyi.</p></div><button className="secondary icon-button" onClick={load}><RefreshCw size={17}/>Refresh</button></section>
    {error&&<p className="error">{error}</p>}
    {!summary?<section className="card coach-onboarding"><UsersRound size={32}/><h2>Buat Coach Workspace</h2><p className="muted">Workspace terpisah menjaga data personal dan client tetap terisolasi.</p><button className="primary icon-button" onClick={createWorkspace}><Plus size={17}/>Aktifkan Coach Mode</button></section>:<>
      <section className="coach-stats"><article className="card"><small>Workspace</small><b>{summary.workspace.name}</b><span>{summary.role}</span></article><article className="card"><small>Plan</small><b>{summary.entitlements.plan}</b><Link href={`/billing?workspaceId=${summary.workspace.id}`}>Kelola billing</Link></article><article className="card"><small>Clients</small><b>{summary.clientCount} / {summary.entitlements.maxClients===-1?'∞':summary.entitlements.maxClients}</b><span>Pending + active</span></article></section>
      <section className="card coach-invite"><div><h2><UserRoundPlus size={20}/> Invite client</h2><p className="muted">Token berlaku 7 hari. Client harus login dan memberi consent eksplisit.</p></div><div className="coach-inline"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="client@email.com"/><button className="primary" onClick={invite}>Buat invite</button></div>{inviteUrl&&<div className="invite-result"><code>{inviteUrl}</code><button className="secondary icon-button" onClick={()=>navigator.clipboard.writeText(inviteUrl)}><Copy size={16}/>Salin</button></div>}</section>
      <section className="coach-list-head"><div><h2>Needs Attention</h2><p className="muted">Risk score deterministik dengan alasan transparan.</p></div><div className="segmented-control"><button className={range===7?'active':''} onClick={()=>setRange(7)}>7 hari</button><button className={range===30?'active':''} onClick={()=>setRange(30)}>30 hari</button></div></section>
      <section className="coach-client-grid">{clients.length===0?<div className="empty-state">Belum ada client. Buat invite pertama.</div>:clients.map(c=><button className="card coach-client-card" key={c.id} onClick={()=>c.status==='ACTIVE'&&openClient(c.id)}><div><b>{c.client.name}</b><small>{c.client.email}</small></div><span className={`risk-badge ${c.risk?.level.toLowerCase()||'pending'}`}>{c.status==='PENDING'?'Pending':`${c.risk?.score} ${c.risk?.level}`}</span>{c.metrics&&<div className="coach-metrics"><span>Completion <b>{c.metrics.completion}%</b></span><span>Inactivity <b>{c.metrics.inactivityDays}d</b></span></div>}{c.risk?.reasons.map((x,i)=><small className="risk-reason" key={i}><AlertTriangle size={13}/>{x.label}</small>)}</button>)}</section>
    </>}
    {detail&&<div className="modal-backdrop" onClick={()=>setDetail(null)}><section className="modal-card coach-detail" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setDetail(null)}>×</button><h2>{detail.client.name}</h2><p>{detail.client.email}</p><div className={`risk-panel ${detail.risk?.level.toLowerCase()}`}><ShieldCheck/><b>Risk {detail.risk?.score}</b>{detail.risk?.reasons.map((x,i)=><span key={i}>{x.label}</span>)}</div><h3>Program aktif</h3>{detail.programs.length?detail.programs.map(p=><p key={p.id}>{p.title}</p>):<p className="muted">Belum ada program aktif.</p>}<h3>Intervention log</h3><div className="duration-presets">{nudgeTemplates.map(template=><button className="secondary" type="button" key={template} onClick={()=>setContent(template)}>{template}</button>)}</div><textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="Catatan private atau pesan nudge..."/><div className="coach-inline"><button className="secondary" onClick={()=>intervention('PRIVATE_NOTE')}>Simpan private note</button><button className="primary icon-button" onClick={()=>intervention('NUDGE')}><Send size={16}/>Catat nudge</button></div><div className="intervention-list">{detail.interventions.map(i=><article key={i.id}><b>{i.type==='NUDGE'?'Nudge (in-app)':'Private note'}</b><p>{i.content}</p><small>{new Date(i.createdAt).toLocaleString('id-ID')}</small></article>)}</div><button className="danger-link" onClick={revoke}>Cabut consent link</button></section></div>}
  </main></div>
}
